//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceDetail_Master
    {
        public long BasicID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<decimal> BasicAllowance { get; set; }
        public Nullable<System.DateTime> BasicAllowancedate { get; set; }
        public Nullable<decimal> HouseAllowance { get; set; }
        public Nullable<System.DateTime> HouseAllowancedate { get; set; }
        public Nullable<decimal> VehicleAllowance { get; set; }
        public Nullable<System.DateTime> VehicleAllowancedate { get; set; }
        public Nullable<decimal> PerformanceAllowance { get; set; }
        public Nullable<System.DateTime> PerformanceAllowancedate { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<System.DateTime> Conveyancedate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
