//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance_Master
    {
        public long AllowanceDetailID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public Nullable<System.DateTime> DA1Date { get; set; }
        public Nullable<System.DateTime> DA2Date { get; set; }
        public Nullable<System.DateTime> OthersDate { get; set; }
        public Nullable<decimal> BasicAllowance1 { get; set; }
        public Nullable<decimal> BasicAllowance2 { get; set; }
        public Nullable<decimal> BasicAllowance3 { get; set; }
        public Nullable<decimal> BasicAllowance4 { get; set; }
        public Nullable<decimal> BasicAllowance5 { get; set; }
        public Nullable<decimal> TotalBasicAllowance { get; set; }
        public Nullable<decimal> HRAPercentage1 { get; set; }
        public Nullable<decimal> HRAPercentage2 { get; set; }
        public Nullable<decimal> HRAPercentage3 { get; set; }
        public Nullable<decimal> HRAPercentage4 { get; set; }
        public Nullable<decimal> HRAPercentage5 { get; set; }
        public Nullable<decimal> HouseRentAllowance1 { get; set; }
        public Nullable<decimal> HouseRentAllowance2 { get; set; }
        public Nullable<decimal> HouseRentAllowance3 { get; set; }
        public Nullable<decimal> HouseRentAllowance4 { get; set; }
        public Nullable<decimal> HouseRentAllowance5 { get; set; }
        public Nullable<decimal> TotalHouseRentAllowance { get; set; }
        public Nullable<decimal> TotalWages1 { get; set; }
        public Nullable<decimal> TotalWages2 { get; set; }
        public Nullable<decimal> TotalWages3 { get; set; }
        public Nullable<decimal> TotalWages4 { get; set; }
        public Nullable<decimal> TotalWages5 { get; set; }
        public Nullable<decimal> GrandTotalWages { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> ConveyancePerDay { get; set; }
        public Nullable<decimal> VehicleAllowance { get; set; }
        public Nullable<decimal> PerformanceAllowance { get; set; }
        public Nullable<long> PerformanceAllowanceStatusID { get; set; }
        public Nullable<long> CityAllowanceStatusID { get; set; }
        public Nullable<long> PFStatusID { get; set; }
        public Nullable<long> ESICStatusID { get; set; }
        public Nullable<decimal> BonusPercentage { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public Nullable<long> BonusStatusID { get; set; }
        public Nullable<decimal> LeaveEnhancementPercentage { get; set; }
        public Nullable<decimal> LeaveEnhancementAmount { get; set; }
        public Nullable<long> LeaveEnhancementStatusID { get; set; }
        public Nullable<decimal> GratuityPercentage { get; set; }
        public Nullable<decimal> GratuityAmount { get; set; }
        public Nullable<long> GratuityStatusID { get; set; }
        public Nullable<decimal> OpeningLeaves { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
