//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckReturn_Mst
    {
        public long CheckBounceID { get; set; }
        public Nullable<long> PaymentID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string InvoiceNumber { get; set; }
        public string BankName { get; set; }
        public string SalesPerson { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<decimal> BounceAmount { get; set; }
        public Nullable<decimal> ChequeReturnCharges { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
