//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Master
    {
        public long DocumentID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public string AadharCard { get; set; }
        public string BankPassBook { get; set; }
        public string BioData { get; set; }
        public string DrivingLicence { get; set; }
        public string ElectionCard { get; set; }
        public string ElectricityBill { get; set; }
        public string IDCard { get; set; }
        public string LeavingCertificate { get; set; }
        public string PanCard { get; set; }
        public string RationCard { get; set; }
        public string Rentagreement { get; set; }
        public string Photo { get; set; }
        public string Signechar { get; set; }
        public string FamilyPhoto { get; set; }
        public string Passport { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string ESICCard { get; set; }
        public string ESIPehchanCard { get; set; }
        public string MedicalFitnessCirtificate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
