//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicMenuMaster
    {
        public long MenuID { get; set; }
        public string DisplayName { get; set; }
        public string SystemName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> MainTier { get; set; }
        public Nullable<int> SubTier { get; set; }
        public Nullable<int> ThirdTier { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsActiveLevelZero { get; set; }
        public string Area { get; set; }
    }
}
