//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense_Mst
    {
        public long ExpenseID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string ShipTo { get; set; }
        public string Tax { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<long> ExpenseTypeID { get; set; }
        public string DeliveryChallanNumber { get; set; }
        public Nullable<System.DateTime> DeliveryChallanDate { get; set; }
        public string EWayNumber { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> TDSCategoryID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
