//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesVoucher_Mst
    {
        public long ExpensesVoucherID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<System.DateTime> DateofVoucher { get; set; }
        public string VoucherNumber { get; set; }
        public string Pay { get; set; }
        public Nullable<long> DebitAccountTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillNumber { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string RemarksL1 { get; set; }
        public string RemarksL2 { get; set; }
        public string RemarksL3 { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsDactive { get; set; }
        public string Identification { get; set; }
    }
}
