//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportOrderQty_Mst
    {
        public long OrderQtyID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> CategoryTypeID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> ProductQtyID { get; set; }
        public string PackateInEachCarton { get; set; }
        public string CartonNo { get; set; }
        public Nullable<int> Carton { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> InvoiceTotalAmt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
