//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportOrder_Mst
    {
        public long OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CountryOfOrigin { get; set; }
        public string CountryOfFinalDestination { get; set; }
        public string PreCarriageBy { get; set; }
        public string PlaceOfReceiptByPreCarrier { get; set; }
        public string VesselName { get; set; }
        public string PortofLoading { get; set; }
        public string PortofDischarge { get; set; }
        public string FinalDestination { get; set; }
        public string Delivery { get; set; }
        public string Payment { get; set; }
        public string BuyersOrderNo { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<int> TotalPkgs { get; set; }
        public string ContainerNo { get; set; }
        public string InsuranceText { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public string FreightText { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> GrandInvoiceTotalAmt { get; set; }
        public Nullable<bool> IsFinalised { get; set; }
        public Nullable<decimal> Rupees { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
