//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSixteenDetail_Mst
    {
        public long FormSixteenDetailID { get; set; }
        public Nullable<decimal> StandardDeduction { get; set; }
        public Nullable<decimal> UnderSection80C { get; set; }
        public Nullable<decimal> HealthInsurancePremiaUnderSection80D { get; set; }
        public Nullable<decimal> InterestOn80E { get; set; }
        public Nullable<decimal> UnderSection80TTA { get; set; }
        public Nullable<decimal> RebateUnderSection87A { get; set; }
        public Nullable<decimal> PensionUnderSection80CCD_1 { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
