//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSixteen_Mst
    {
        public long FormSixteenID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<decimal> StandardDeductions { get; set; }
        public Nullable<decimal> HousingLoanPrincipal { get; set; }
        public Nullable<decimal> ELSS { get; set; }
        public Nullable<decimal> PPF { get; set; }
        public Nullable<decimal> LifeInsurance { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> TDSSalary { get; set; }
        public Nullable<decimal> HealthInsurancePremiaUnderSection80D { get; set; }
        public Nullable<decimal> HealthInsurancePremiaUnderSection80D_Actual { get; set; }
        public Nullable<decimal> InterestOn80E { get; set; }
        public Nullable<decimal> InterestOn80E_Actual { get; set; }
        public Nullable<decimal> UnderSection80G { get; set; }
        public Nullable<decimal> UnderSection80TTA { get; set; }
        public Nullable<decimal> UnderSection80TTA_Actual { get; set; }
        public Nullable<decimal> PensionUnderSection80CCD_1 { get; set; }
        public Nullable<decimal> PensionUnderSection80CCD_1_Actual { get; set; }
        public Nullable<bool> IsFiftyPer { get; set; }
        public Nullable<decimal> RebateUnderSection87A { get; set; }
        public Nullable<decimal> UnderSection80C { get; set; }
        public Nullable<decimal> TaxSlabPer { get; set; }
        public Nullable<decimal> SurchargeSlabPer { get; set; }
        public Nullable<decimal> EducationSlabPer { get; set; }
        public Nullable<decimal> IncomeFrom { get; set; }
        public Nullable<decimal> IncomeTo { get; set; }
        public Nullable<decimal> TaxOnTotalIncome { get; set; }
        public Nullable<decimal> TaxOnTotalIncome_one { get; set; }
        public Nullable<decimal> RebateUnderSection87A_Income { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> FormSixteenEHRA { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
