//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSixteenTexableIncome
    {
        public long FormSixteenTexableID { get; set; }
        public Nullable<long> FormSixteenDetailID { get; set; }
        public Nullable<decimal> IncomeFrom { get; set; }
        public Nullable<decimal> IncomeTo { get; set; }
        public Nullable<decimal> TaxOnTotalIncome { get; set; }
        public Nullable<decimal> TaxOnTotalIncome_one { get; set; }
        public Nullable<decimal> RebateUnderSection87A_Income { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
