//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Godown_Mst
    {
        public long GodownID { get; set; }
        public string GodownName { get; set; }
        public string GodownPhone { get; set; }
        public string GodownAddress1 { get; set; }
        public string GodownAddress2 { get; set; }
        public string GodownFSSAINumber { get; set; }
        public string GodownCode { get; set; }
        public string GodownNote { get; set; }
        public string Place { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> GSTNumber { get; set; }
        public string CashOption { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public Nullable<decimal> ChillarAmount { get; set; }
    }
}
