//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gratuity_Hisab_Mst
    {
        public long Gratuity_Hisab_ID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<decimal> LastDrawnSalary { get; set; }
        public Nullable<int> TotalMonth { get; set; }
        public Nullable<decimal> Gratuity { get; set; }
        public Nullable<decimal> AdditionalGratuity { get; set; }
        public Nullable<decimal> TotalGratuity { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> TotalEarnedSalary { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public Nullable<decimal> AdditionalBonusAmount { get; set; }
        public Nullable<decimal> TotalBonusAmount { get; set; }
        public Nullable<decimal> LastDrawnSalaryLeaveEnhancement { get; set; }
        public Nullable<decimal> ClosingLeaves { get; set; }
        public Nullable<decimal> LeaveEncashment { get; set; }
        public Nullable<decimal> AdditionalLeaveEncashment { get; set; }
        public Nullable<decimal> TotalLeaveEncashment { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<long> WitnessOneID { get; set; }
        public Nullable<long> WitnessTwoID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
