//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroundStock_Inward_Mst
    {
        public long InwardID { get; set; }
        public Nullable<long> PurchaseQtyID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<decimal> ClosingQty { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
