//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroundStock_Mst
    {
        public long GroundStockID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> GroundStockQuantity { get; set; }
        public Nullable<decimal> MinGroundStockQuantity { get; set; }
        public string GroundStockDescription { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
