//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardOutward_Mst
    {
        public long InwardID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public Nullable<decimal> ChillarInward { get; set; }
        public Nullable<System.DateTime> WholesaleAssignedDate { get; set; }
        public Nullable<decimal> WholesaleCash { get; set; }
        public Nullable<System.DateTime> RetailAssignedDate { get; set; }
        public Nullable<decimal> RetailCash { get; set; }
        public Nullable<System.DateTime> WholesaleTempoDate1 { get; set; }
        public string WholesaleVehicleNo1 { get; set; }
        public Nullable<decimal> WholesaleTempoAmount1 { get; set; }
        public Nullable<System.DateTime> WholesaleTempoDate2 { get; set; }
        public string WholesaleVehicleNo2 { get; set; }
        public Nullable<decimal> WholesaleTempoAmount2 { get; set; }
        public Nullable<System.DateTime> WholesaleTempoDate3 { get; set; }
        public string WholesaleVehicleNo3 { get; set; }
        public Nullable<decimal> WholesaleTempoAmount3 { get; set; }
        public Nullable<System.DateTime> RetailTempoDate1 { get; set; }
        public string RetailVehicleNo1 { get; set; }
        public Nullable<decimal> RetailTempoAmount1 { get; set; }
        public Nullable<System.DateTime> RetailTempoDate2 { get; set; }
        public string RetailVehicleNo2 { get; set; }
        public Nullable<decimal> RetailTempoAmount2 { get; set; }
        public Nullable<System.DateTime> RetailTempoDate3 { get; set; }
        public string RetailVehicleNo3 { get; set; }
        public Nullable<decimal> RetailTempoAmount3 { get; set; }
        public Nullable<decimal> TotalInward { get; set; }
        public Nullable<decimal> ChillarOutward { get; set; }
        public Nullable<System.DateTime> ExpensesDate { get; set; }
        public Nullable<decimal> TotalExpenses { get; set; }
        public Nullable<decimal> TransferVB2 { get; set; }
        public Nullable<decimal> TransferVB3 { get; set; }
        public Nullable<long> BankID1 { get; set; }
        public Nullable<decimal> BankDepositeAmount1 { get; set; }
        public Nullable<long> BankID2 { get; set; }
        public Nullable<decimal> BankDepositeAmount2 { get; set; }
        public Nullable<long> BankID3 { get; set; }
        public Nullable<decimal> BankDepositeAmount3 { get; set; }
        public Nullable<decimal> TotalOutward { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> OpeningChillar { get; set; }
        public Nullable<decimal> ClosingChillar { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsDactive { get; set; }
    }
}
