//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication_Mst
    {
        public long LeaveApplicationID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<decimal> ClosingLeaves { get; set; }
        public Nullable<decimal> ClosingAdvance { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Reason { get; set; }
        public string GoingTo { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public string AdvanceReason { get; set; }
        public Nullable<decimal> DeductionPerMonthAmount { get; set; }
        public Nullable<int> LeaveStatusID { get; set; }
        public Nullable<System.DateTime> ApprovalFromDate { get; set; }
        public Nullable<System.DateTime> ApprovalToDate { get; set; }
        public Nullable<decimal> ApprovalAdvanceAmount { get; set; }
        public Nullable<long> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAdvanceAmount { get; set; }
    }
}
