//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewDailyAttendance_Mst
    {
        public long DAttendanceID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public string AEmployeeName { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public Nullable<int> AYear { get; set; }
        public Nullable<int> AMonth { get; set; }
        public string ShiftStartTime { get; set; }
        public Nullable<System.DateTime> ShiftStartDateTime { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string TimeIn { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public string TimeOut { get; set; }
        public Nullable<decimal> TotalHoursWorked { get; set; }
        public Nullable<decimal> OT { get; set; }
        public string ShiftEndTime { get; set; }
        public string Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
