//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineProductQty_Mst
    {
        public long OnlineProductQtyID { get; set; }
        public long ProductID { get; set; }
        public Nullable<decimal> OnlineProductPrice { get; set; }
        public Nullable<long> OnlineQty { get; set; }
        public Nullable<long> OnlineUnitID { get; set; }
        public Nullable<decimal> Factoring { get; set; }
        public Nullable<decimal> FactoringAmount { get; set; }
        public Nullable<decimal> PremiumPercentage { get; set; }
        public Nullable<decimal> PremiumAmount { get; set; }
        public Nullable<decimal> OnlineTotalAmount { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
    }
}
