//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Mst
    {
        public long OrderID { get; set; }
        public string InvoiceNumber { get; set; }
        public long CustomerID { get; set; }
        public string ShipTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Tax { get; set; }
        public string OrderRef { get; set; }
        public Nullable<decimal> FinaOrderlTotal { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public bool PendingDelivery { get; set; }
        public Nullable<System.DateTime> DeliveryCompletedDate { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public string PDFName { get; set; }
        public bool RemotePrint { get; set; }
        public Nullable<bool> IsTCSApplicable { get; set; }
        public Nullable<long> OnlineOrderID { get; set; }
    }
}
