//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pouch_Mst
    {
        public long PouchID { get; set; }
        public long PouchNameID { get; set; }
        public string PouchDescription { get; set; }
        public Nullable<int> PouchQuantity { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> KG { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> MinPouchQuantity { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
