//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreMix_Mst
    {
        public long PremixID { get; set; }
        public Nullable<decimal> RatePerKG { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public Nullable<decimal> Gasara { get; set; }
        public Nullable<decimal> GasaraAmount { get; set; }
        public Nullable<decimal> GrindingCharge { get; set; }
        public Nullable<decimal> PackingCharge { get; set; }
        public Nullable<decimal> MakingCharge { get; set; }
        public Nullable<decimal> Padtar { get; set; }
        public Nullable<decimal> SellRateWholesale { get; set; }
        public Nullable<decimal> MarginWholesale { get; set; }
        public Nullable<decimal> SellRateRetail { get; set; }
        public Nullable<decimal> MarginRetail { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
