//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Mst
    {
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductAlternateName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> PouchNameID { get; set; }
        public string ProductDescription { get; set; }
        public string HSNNumber { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> HFor { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> SlabForGST { get; set; }
    }
}
