//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurcahsePayment_Mst
    {
        public long PaymentID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BillNumber { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public decimal ByCash { get; set; }
        public Nullable<long> BankID { get; set; }
        public Nullable<bool> ByCheque { get; set; }
        public string ChequeNo { get; set; }
        public bool ByCard { get; set; }
        public string TypeOfCard { get; set; }
        public bool ByOnline { get; set; }
        public string UTRNumber { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<decimal> AdjustAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
    }
}
