//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseQty_Mst
    {
        public long PurchaseQtyID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> CategoryTypeID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string HSNNumber { get; set; }
        public string VakalNumber { get; set; }
        public Nullable<int> NoofBags { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> RatePerKG { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> WeightPerBag { get; set; }
        public Nullable<decimal> RatePerBags { get; set; }
        public Nullable<decimal> PackingChargesBag { get; set; }
        public Nullable<decimal> TotalPackingCharge { get; set; }
        public Nullable<decimal> Hamali { get; set; }
        public Nullable<decimal> LessDiscount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> APMC { get; set; }
        public Nullable<decimal> APMCAmount { get; set; }
        public Nullable<decimal> TotalTaxableAmount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> CGSTTax { get; set; }
        public Nullable<decimal> CGSTTaxAmount { get; set; }
        public Nullable<decimal> SGSTTax { get; set; }
        public Nullable<decimal> SGSTTaxAmount { get; set; }
        public Nullable<decimal> IGSTTax { get; set; }
        public Nullable<decimal> IGSTTaxAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> TransportInward { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<decimal> TCSAmount { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> TDSTax { get; set; }
        public Nullable<decimal> TDSTaxAmount { get; set; }
        public Nullable<decimal> AmountAfterTDS { get; set; }
        public Nullable<decimal> TotalPurchaseBillAmount { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsInward { get; set; }
    }
}
