//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetCustomerGroupMst
    {
        public long CustomerGroupID { get; set; }
        public string CustomerGroupName { get; set; }
        public string CustomerGroupAddress1 { get; set; }
        public string CustomerGroupAddress2 { get; set; }
        public long AreaID { get; set; }
        public string CustomerGroupDescription { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<bool> IsShow { get; set; }
    }
}
