//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetCustomerCategoryDiscountMst
    {
        public long CategoryDiscountID { get; set; }
        public long CustomerID { get; set; }
        public string Contract { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public long CategoryID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public bool IsDelete { get; set; }
    }
}
