//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetOrderQtyMst
    {
        public long OrderQtyID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> ProductQtyID { get; set; }
        public Nullable<long> CategoryTypeID { get; set; }
        public string TaxName { get; set; }
        public decimal Quantity { get; set; }
        public decimal UpdateQuantity { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> SPDiscount { get; set; }
        public Nullable<decimal> TexableAmount { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<decimal> ProductMRP { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> TCSTax { get; set; }
        public Nullable<decimal> TCSTaxAmount { get; set; }
        public Nullable<decimal> GrandInvoiceTotal { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> SectionID { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public bool PendingDelivery { get; set; }
        public Nullable<System.DateTime> DeliveryCompletedDate { get; set; }
        public string ArticleCode { get; set; }
        public string EWayNumber { get; set; }
        public Nullable<long> TransportID { get; set; }
        public string DocketNo { get; set; }
        public Nullable<System.DateTime> DocketDate { get; set; }
        public Nullable<System.DateTime> VehicleAssignedDate { get; set; }
        public string PDFName { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<bool> IsPackDone { get; set; }
    }
}
