//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetOrderMst
    {
        public long OrderID { get; set; }
        public string InvoiceNumber { get; set; }
        public long CustomerID { get; set; }
        public string Tax { get; set; }
        public string ShipTo { get; set; }
        public string BillTo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string PONumber { get; set; }
        public string OrderNote { get; set; }
        public Nullable<decimal> FinaOrderlTotal { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<bool> PendingDelivery { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public bool IsFinalised { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<bool> IsPrintPackList { get; set; }
        public Nullable<bool> IsTCSApplicable { get; set; }
        public Nullable<bool> IsCheckDone { get; set; }
    }
}
