//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetPaymentMst
    {
        public long PaymentID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Containers { get; set; }
        public Nullable<decimal> ByCash { get; set; }
        public bool ByCheque { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string IFCCode { get; set; }
        public bool BySign { get; set; }
        public bool ByCard { get; set; }
        public string BankNameForCard { get; set; }
        public string TypeOfCard { get; set; }
        public bool ByOnline { get; set; }
        public string BankNameForOnline { get; set; }
        public string UTRNumber { get; set; }
        public Nullable<System.DateTime> OnlinePaymentDate { get; set; }
        public decimal AdjustAmount { get; set; }
        public Nullable<int> VehicleNo { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public bool IsDelivered { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
        public bool IsInvoiceExist { get; set; }
        public bool IsCreditNote { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<bool> IsInwardTempo { get; set; }
        public Nullable<bool> IsCheckBounce { get; set; }
        public Nullable<decimal> ChequeReturnAmount { get; set; }
        public Nullable<decimal> OutAmount { get; set; }
    }
}
