//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetProductMst
    {
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> BestBeforeMonthID { get; set; }
        public string ProductDescription { get; set; }
        public string HSNNumber { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> HFor { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public string ContentValue { get; set; }
        public string NutritionValue { get; set; }
        public string PlaceOfOrigin { get; set; }
        public string Protein { get; set; }
        public string Fat { get; set; }
        public string Carbohydrate { get; set; }
        public string TotalEnergy { get; set; }
        public string Information { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
