//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetProductQtyMst
    {
        public long ProductQtyID { get; set; }
        public long ProductID { get; set; }
        public Nullable<bool> IsSelect { get; set; }
        public long ProductQuantity { get; set; }
        public Nullable<long> UnitID { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal ProductMRP { get; set; }
        public Nullable<decimal> GramPerKG { get; set; }
        public string ProductBarcode { get; set; }
        public Nullable<long> PouchNameID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
    }
}
