//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetPackSummaryQty_Mst
    {
        public long PackSummaryQtyID { get; set; }
        public long PackSummaryID { get; set; }
        public long OrderQtyID { get; set; }
        public long ProductID { get; set; }
        public long ProductQtyID { get; set; }
        public decimal Quantity { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
    }
}
