//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetPackSummary_Mst
    {
        public long PackSummaryID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> OrderQtyID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Bag { get; set; }
        public Nullable<int> Tray { get; set; }
        public Nullable<int> Zabla { get; set; }
        public Nullable<int> Box { get; set; }
        public Nullable<decimal> TotalKG { get; set; }
        public Nullable<System.DateTime> DeliveryAssignDate { get; set; }
        public Nullable<int> VehicleNo { get; set; }
        public string Tag { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
