//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetProdQtyGui
    {
        public long RetProdGuiQtyID { get; set; }
        public Nullable<long> RetProdGuiID { get; set; }
        public Nullable<long> ProductQtyID { get; set; }
        public string ProductQtyGui { get; set; }
        public Nullable<int> UnitGuiID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
