//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnOrderQty_Mst
    {
        public long ReturnedOrderQtyID { get; set; }
        public string CreditMemoNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public long OrderQtyID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public long ProductID { get; set; }
        public Nullable<long> CategoryTypeID { get; set; }
        public decimal ReturnedQuantity { get; set; }
        public decimal ReturnedSaleRate { get; set; }
        public Nullable<decimal> BillDiscount { get; set; }
        public Nullable<decimal> TaxReversed { get; set; }
        public Nullable<decimal> CreditedFinalTotal { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
