//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPayment_Mst
    {
        public long PaymentID { get; set; }
        public Nullable<long> MonthID { get; set; }
        public Nullable<long> YearID { get; set; }
        public Nullable<long> GodownID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<long> BankID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<long> SalarySheetID { get; set; }
        public Nullable<decimal> NetWagesPaid { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> Goods { get; set; }
        public Nullable<decimal> AnyOtherDeductions1 { get; set; }
        public Nullable<decimal> AnyOtherDeductions2 { get; set; }
        public Nullable<decimal> FinalTotalDeductions { get; set; }
        public Nullable<decimal> NetWagesToPay { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
