//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySheet_Master
    {
        public long SalarySheetID { get; set; }
        public Nullable<long> EmployeeCode { get; set; }
        public Nullable<int> MonthID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> AdditionalPresent { get; set; }
        public Nullable<int> TotalPresent { get; set; }
        public Nullable<int> Sunday { get; set; }
        public Nullable<int> AdditionalSunday { get; set; }
        public Nullable<int> TotalSunday { get; set; }
        public Nullable<int> Holiday { get; set; }
        public Nullable<int> AdditionalHoliday { get; set; }
        public Nullable<int> TotalHoliday { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<int> AdditionalAbsent { get; set; }
        public Nullable<int> TotalAbsent { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> TotalDaysIntheMonth { get; set; }
        public Nullable<decimal> BasicAllowance { get; set; }
        public Nullable<decimal> HouseRentAllowance { get; set; }
        public Nullable<decimal> TotalBasic { get; set; }
        public Nullable<decimal> EarnedBasicWages { get; set; }
        public Nullable<decimal> EarnedHouseRentAllowance { get; set; }
        public Nullable<decimal> TotalEarnedWages { get; set; }
        public Nullable<decimal> CityAllowanceMinutes { get; set; }
        public Nullable<decimal> AdditionalCityAllowanceMinutes { get; set; }
        public Nullable<decimal> CityAllowanceHours { get; set; }
        public Nullable<decimal> CityAllowance { get; set; }
        public Nullable<decimal> AdditionalCityAllowance { get; set; }
        public Nullable<decimal> TotalCityAllowance { get; set; }
        public Nullable<decimal> VehicleAllowance { get; set; }
        public Nullable<decimal> AdditionalVehicleAllowance { get; set; }
        public Nullable<decimal> TotalVehicleAllowance { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> AdditionalConveyance { get; set; }
        public Nullable<decimal> TotalConveyance { get; set; }
        public Nullable<decimal> PerformanceAllowance { get; set; }
        public Nullable<decimal> AdditionalPerformanceAllowance { get; set; }
        public Nullable<decimal> TotalPerformanceAllowance { get; set; }
        public Nullable<decimal> GrossWagesPayable { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> ESIC { get; set; }
        public Nullable<decimal> PT { get; set; }
        public Nullable<decimal> MLWF { get; set; }
        public Nullable<decimal> TotalDeductions { get; set; }
        public Nullable<decimal> NetWagesPaid { get; set; }
        public Nullable<decimal> OpeningLeaves { get; set; }
        public Nullable<decimal> EarnedLeaves { get; set; }
        public Nullable<decimal> AvailedLeaves { get; set; }
        public Nullable<decimal> AdditionalAvailedLeaves { get; set; }
        public Nullable<decimal> TotalAvailedLeaves { get; set; }
        public Nullable<decimal> ClosingLeaves { get; set; }
        public Nullable<decimal> AdditionalClosingLeaves { get; set; }
        public Nullable<decimal> TotalClosingLeaves { get; set; }
        public Nullable<decimal> OpeningAdvance { get; set; }
        public Nullable<decimal> Addition { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> ClosingAdvance { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> Goods { get; set; }
        public Nullable<decimal> AnyOtherDeductions1 { get; set; }
        public Nullable<decimal> AnyOtherDeductions2 { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
