//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail_Mst
    {
        public long VehicleDetailID { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string RCCertificate { get; set; }
        public Nullable<System.DateTime> RCNoValidity { get; set; }
        public string FitnessCertificate { get; set; }
        public Nullable<System.DateTime> FitnessValidity { get; set; }
        public string PermitCertificate { get; set; }
        public Nullable<System.DateTime> PermitValidity { get; set; }
        public string PUCCertificate { get; set; }
        public Nullable<System.DateTime> PUCValidity { get; set; }
        public string InsuranceCertificate { get; set; }
        public Nullable<System.DateTime> InsuranceValidity { get; set; }
        public string AdvertisementCertificate { get; set; }
        public Nullable<System.DateTime> AdvertisementValidity { get; set; }
        public string SpeedGovernorCertificate { get; set; }
        public Nullable<System.DateTime> SpeedGovernorCertificateValidity { get; set; }
        public string FSSAICertificate { get; set; }
        public Nullable<System.DateTime> FSSAICertificateValidity { get; set; }
        public string GreenTaxCertificate { get; set; }
        public Nullable<System.DateTime> GreenTaxCertificateValidity { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<System.DateTime> InstallmentAmountDate { get; set; }
        public Nullable<decimal> OneTimeTax { get; set; }
        public Nullable<System.DateTime> OneTimeTaxDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
