//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInwardCost_Mst
    {
        public long VehicleInwardCostID { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> InwardID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<long> VehicleDetailID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsVehicleStatus { get; set; }
    }
}
