//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCosting_Mst
    {
        public long VehicleCostingID { get; set; }
        public Nullable<int> WholesaleVehicleNo1 { get; set; }
        public Nullable<System.DateTime> WholesaleVehicleNo1Date { get; set; }
        public Nullable<decimal> WholesaleInvioceAmount1 { get; set; }
        public Nullable<decimal> WholesaleTotalKG1 { get; set; }
        public Nullable<int> WholesaleVehicleNo2 { get; set; }
        public Nullable<System.DateTime> WholesaleVehicleNo2Date { get; set; }
        public Nullable<decimal> WholesaleInvioceAmount2 { get; set; }
        public Nullable<decimal> WholesaleTotalKG2 { get; set; }
        public Nullable<int> RetailVehicleNo1 { get; set; }
        public Nullable<System.DateTime> RetailVehicleNo1Date { get; set; }
        public Nullable<decimal> RetailInvioceAmount1 { get; set; }
        public Nullable<decimal> RetailTotalKG1 { get; set; }
        public Nullable<int> RetailVehicleNo2 { get; set; }
        public Nullable<System.DateTime> RetailVehicleNo2Date { get; set; }
        public Nullable<decimal> RetailInvioceAmount2 { get; set; }
        public Nullable<decimal> RetailTotalKG2 { get; set; }
        public Nullable<decimal> GrandInvoiceAmount { get; set; }
        public Nullable<decimal> GrandTotalKG { get; set; }
        public Nullable<long> VehicleDetailID { get; set; }
        public string AreaName { get; set; }
        public long DeliveryPerson1 { get; set; }
        public long DeliveryPerson2 { get; set; }
        public long DeliveryPerson3 { get; set; }
        public long DeliveryPerson4 { get; set; }
        public Nullable<decimal> OpeningKM { get; set; }
        public Nullable<decimal> ClosingKM { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<decimal> DieselOpeningKM { get; set; }
        public Nullable<decimal> DieselKM { get; set; }
        public Nullable<decimal> DieselAmount { get; set; }
        public Nullable<decimal> DieselLiter { get; set; }
        public Nullable<decimal> RepairingAmount { get; set; }
        public string RepairingDetail { get; set; }
        public Nullable<decimal> RepairingAmount2 { get; set; }
        public string RepairingDetail2 { get; set; }
        public Nullable<decimal> RepairingAmount3 { get; set; }
        public string RepairingDetail3 { get; set; }
        public Nullable<decimal> TollAmount { get; set; }
        public string TollDetail { get; set; }
        public Nullable<decimal> BharaiAmount { get; set; }
        public string BharaiDetail { get; set; }
        public Nullable<decimal> MiscellaneousAmount1 { get; set; }
        public string MiscellaneousDetail1 { get; set; }
        public Nullable<decimal> MiscellaneousAmount2 { get; set; }
        public string MiscellaneousDetail2 { get; set; }
        public Nullable<decimal> MiscellaneousAmount3 { get; set; }
        public string MiscellaneousDetail3 { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
