//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VirakiEntities : DbContext
    {
        public VirakiEntities()
            : base("name=VirakiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BestBeforeMonth> BestBeforeMonths { get; set; }
        public virtual DbSet<Category_Mst> Category_Mst { get; set; }
        public virtual DbSet<Challan_Mst> Challan_Mst { get; set; }
        public virtual DbSet<CustomerGroup_Mst> CustomerGroup_Mst { get; set; }
        public virtual DbSet<DeliveryAllocation_Mst> DeliveryAllocation_Mst { get; set; }
        public virtual DbSet<Driver_Mst> Driver_Mst { get; set; }
        public virtual DbSet<Event_Mst> Event_Mst { get; set; }
        public virtual DbSet<EventDate_Mst> EventDate_Mst { get; set; }
        public virtual DbSet<Login_Mst> Login_Mst { get; set; }
        public virtual DbSet<PackageStation_Mst> PackageStation_Mst { get; set; }
        public virtual DbSet<PackedBy_Mst> PackedBy_Mst { get; set; }
        public virtual DbSet<ProductQty_Mst> ProductQty_Mst { get; set; }
        public virtual DbSet<RetAreaMst> RetAreaMsts { get; set; }
        public virtual DbSet<RetChallanMst> RetChallanMsts { get; set; }
        public virtual DbSet<RetDeliveryAllocationMst> RetDeliveryAllocationMsts { get; set; }
        public virtual DbSet<RetProductCategoryMst> RetProductCategoryMsts { get; set; }
        public virtual DbSet<RetTaxMst> RetTaxMsts { get; set; }
        public virtual DbSet<ReturnOrderQty_Mst> ReturnOrderQty_Mst { get; set; }
        public virtual DbSet<ReturnRetailOrderQtyMst> ReturnRetailOrderQtyMsts { get; set; }
        public virtual DbSet<Role_Mst> Role_Mst { get; set; }
        public virtual DbSet<Tax_Mst> Tax_Mst { get; set; }
        public virtual DbSet<TimeZoneMaster> TimeZoneMasters { get; set; }
        public virtual DbSet<Unit_Mst> Unit_Mst { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<RetProductArticleCodeMst> RetProductArticleCodeMsts { get; set; }
        public virtual DbSet<DynamicMenuMaster> DynamicMenuMasters { get; set; }
        public virtual DbSet<MachineRawPunch> MachineRawPunches { get; set; }
        public virtual DbSet<RetPackSummaryQty_Mst> RetPackSummaryQty_Mst { get; set; }
        public virtual DbSet<User_Mst> User_Mst { get; set; }
        public virtual DbSet<Document_Master> Document_Master { get; set; }
        public virtual DbSet<AuthorizeMaster> AuthorizeMasters { get; set; }
        public virtual DbSet<RetGodownMst> RetGodownMsts { get; set; }
        public virtual DbSet<RetTransportMst> RetTransportMsts { get; set; }
        public virtual DbSet<Transport_Mst> Transport_Mst { get; set; }
        public virtual DbSet<ChallanQty_Mst> ChallanQty_Mst { get; set; }
        public virtual DbSet<RetChallanQtyMst> RetChallanQtyMsts { get; set; }
        public virtual DbSet<RetPackSummary_Mst> RetPackSummary_Mst { get; set; }
        public virtual DbSet<AllowanceDetail_Master> AllowanceDetail_Master { get; set; }
        public virtual DbSet<DailyAttendance_Mst> DailyAttendance_Mst { get; set; }
        public virtual DbSet<GuiLabel> GuiLabels { get; set; }
        public virtual DbSet<GuiLanguage> GuiLanguages { get; set; }
        public virtual DbSet<RetProdGui> RetProdGuis { get; set; }
        public virtual DbSet<RetProdQtyGui> RetProdQtyGuis { get; set; }
        public virtual DbSet<RetUnitMst> RetUnitMsts { get; set; }
        public virtual DbSet<Licence_Mst> Licence_Mst { get; set; }
        public virtual DbSet<VehicleDetail_Mst> VehicleDetail_Mst { get; set; }
        public virtual DbSet<DebitAccountType_Mst> DebitAccountType_Mst { get; set; }
        public virtual DbSet<Godown_Mst> Godown_Mst { get; set; }
        public virtual DbSet<TransferAmount_Mst> TransferAmount_Mst { get; set; }
        public virtual DbSet<RetCustomerGroupMst> RetCustomerGroupMsts { get; set; }
        public virtual DbSet<VehicleCosting_Mst> VehicleCosting_Mst { get; set; }
        public virtual DbSet<SupplierContact_Master> SupplierContact_Master { get; set; }
        public virtual DbSet<PurchaseType_Mst> PurchaseType_Mst { get; set; }
        public virtual DbSet<Broker_Mst> Broker_Mst { get; set; }
        public virtual DbSet<PurchaseDebitAccountType_Mst> PurchaseDebitAccountType_Mst { get; set; }
        public virtual DbSet<PurchaseProduct_Mst> PurchaseProduct_Mst { get; set; }
        public virtual DbSet<PurcahsePayment_Mst> PurcahsePayment_Mst { get; set; }
        public virtual DbSet<Country_Mst> Country_Mst { get; set; }
        public virtual DbSet<CountryWiseProductName_Mst> CountryWiseProductName_Mst { get; set; }
        public virtual DbSet<ExportOrderQty_Mst> ExportOrderQty_Mst { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<RetCustomerAddress> RetCustomerAddresses { get; set; }
        public virtual DbSet<ExportOrder_Mst> ExportOrder_Mst { get; set; }
        public virtual DbSet<Bank_Mst> Bank_Mst { get; set; }
        public virtual DbSet<InwardOutward_Mst> InwardOutward_Mst { get; set; }
        public virtual DbSet<DeActiveHistory_Mst> DeActiveHistory_Mst { get; set; }
        public virtual DbSet<ExpenseType_Mst> ExpenseType_Mst { get; set; }
        public virtual DbSet<ExpenseDebitAccountType_Mst> ExpenseDebitAccountType_Mst { get; set; }
        public virtual DbSet<ExpenseProduct_Mst> ExpenseProduct_Mst { get; set; }
        public virtual DbSet<ExpenseSupplierContact_Master> ExpenseSupplierContact_Master { get; set; }
        public virtual DbSet<ExpensePayment_Mst> ExpensePayment_Mst { get; set; }
        public virtual DbSet<PouchCost_Mst> PouchCost_Mst { get; set; }
        public virtual DbSet<UtilityCost_Mst> UtilityCost_Mst { get; set; }
        public virtual DbSet<BarcodeCount_Mst> BarcodeCount_Mst { get; set; }
        public virtual DbSet<Festival_Mst> Festival_Mst { get; set; }
        public virtual DbSet<AllowanceStatus_Mst> AllowanceStatus_Mst { get; set; }
        public virtual DbSet<EarnedLeaves_Mst> EarnedLeaves_Mst { get; set; }
        public virtual DbSet<ESIC_Mst> ESIC_Mst { get; set; }
        public virtual DbSet<MLWF_Mst> MLWF_Mst { get; set; }
        public virtual DbSet<PF_Mst> PF_Mst { get; set; }
        public virtual DbSet<PT_Mst> PT_Mst { get; set; }
        public virtual DbSet<Gratuity_Mst> Gratuity_Mst { get; set; }
        public virtual DbSet<LeaveEncashment_Mst> LeaveEncashment_Mst { get; set; }
        public virtual DbSet<NewDailyAttendance_Mst> NewDailyAttendance_Mst { get; set; }
        public virtual DbSet<TDSCategory_Mst> TDSCategory_Mst { get; set; }
        public virtual DbSet<Expense_Mst> Expense_Mst { get; set; }
        public virtual DbSet<Allowance_Master> Allowance_Master { get; set; }
        public virtual DbSet<SalaryPayment_Mst> SalaryPayment_Mst { get; set; }
        public virtual DbSet<Delivery_Mst> Delivery_Mst { get; set; }
        public virtual DbSet<RetDeliveryMst> RetDeliveryMsts { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<VehicleInwardCost_Mst> VehicleInwardCost_Mst { get; set; }
        public virtual DbSet<ExpensesVoucher_Mst> ExpensesVoucher_Mst { get; set; }
        public virtual DbSet<WholesaleExpenseVoucherPayment_Mst> WholesaleExpenseVoucherPayment_Mst { get; set; }
        public virtual DbSet<RetailExpenseVoucherPayment_Mst> RetailExpenseVoucherPayment_Mst { get; set; }
        public virtual DbSet<TCS_Mst> TCS_Mst { get; set; }
        public virtual DbSet<RetOrderMst> RetOrderMsts { get; set; }
        public virtual DbSet<ExpenseQty_Mst> ExpenseQty_Mst { get; set; }
        public virtual DbSet<Utility_Mst> Utility_Mst { get; set; }
        public virtual DbSet<UtilityTransfer_Mst> UtilityTransfer_Mst { get; set; }
        public virtual DbSet<UtilityInwardOutward_Mst> UtilityInwardOutward_Mst { get; set; }
        public virtual DbSet<UtilityName_Mst> UtilityName_Mst { get; set; }
        public virtual DbSet<Pouch_Mst> Pouch_Mst { get; set; }
        public virtual DbSet<PouchInwardOutward_Mst> PouchInwardOutward_Mst { get; set; }
        public virtual DbSet<PouchTransfer_Mst> PouchTransfer_Mst { get; set; }
        public virtual DbSet<LeaveApplication_Mst> LeaveApplication_Mst { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Resignation_Mst> Resignation_Mst { get; set; }
        public virtual DbSet<Gratuity_Hisab_Mst> Gratuity_Hisab_Mst { get; set; }
        public virtual DbSet<EInvoice_Mst> EInvoice_Mst { get; set; }
        public virtual DbSet<RetEInvoice_Mst> RetEInvoice_Mst { get; set; }
        public virtual DbSet<AuthToken_Mst> AuthToken_Mst { get; set; }
        public virtual DbSet<EInvoiceCreditMemo_Mst> EInvoiceCreditMemo_Mst { get; set; }
        public virtual DbSet<RetEInvoiceCreditMemo_Mst> RetEInvoiceCreditMemo_Mst { get; set; }
        public virtual DbSet<ReturnOrder_Mst> ReturnOrder_Mst { get; set; }
        public virtual DbSet<ReturnOrderQnty_Mst> ReturnOrderQnty_Mst { get; set; }
        public virtual DbSet<RetReturnOrderMst> RetReturnOrderMsts { get; set; }
        public virtual DbSet<RetReturnOrderQntyMst> RetReturnOrderQntyMsts { get; set; }
        public virtual DbSet<EInvoiceErrorDetails_Mst> EInvoiceErrorDetails_Mst { get; set; }
        public virtual DbSet<RetEInvoiceErrorDetails_Mst> RetEInvoiceErrorDetails_Mst { get; set; }
        public virtual DbSet<EWayBill_Mst> EWayBill_Mst { get; set; }
        public virtual DbSet<RetEWayBill_Mst> RetEWayBill_Mst { get; set; }
        public virtual DbSet<EWayBillChallan_Mst> EWayBillChallan_Mst { get; set; }
        public virtual DbSet<RetEWayBillChallan_Mst> RetEWayBillChallan_Mst { get; set; }
        public virtual DbSet<Currency_Mst> Currency_Mst { get; set; }
        public virtual DbSet<OnlineProductQty_Mst> OnlineProductQty_Mst { get; set; }
        public virtual DbSet<Area_Mst> Area_Mst { get; set; }
        public virtual DbSet<OnlineOrderQty_Mst> OnlineOrderQty_Mst { get; set; }
        public virtual DbSet<PurchaseTDSCategory_Mst> PurchaseTDSCategory_Mst { get; set; }
        public virtual DbSet<Purchase_Mst> Purchase_Mst { get; set; }
        public virtual DbSet<PurchaseQty_Mst> PurchaseQty_Mst { get; set; }
        public virtual DbSet<AreaPincode_SubMst> AreaPincode_SubMst { get; set; }
        public virtual DbSet<Order_Mst> Order_Mst { get; set; }
        public virtual DbSet<OnlineOrder_Mst> OnlineOrder_Mst { get; set; }
        public virtual DbSet<Customer_Mst> Customer_Mst { get; set; }
        public virtual DbSet<RetCustomerMst> RetCustomerMsts { get; set; }
        public virtual DbSet<ExpenseSupplier_Master> ExpenseSupplier_Master { get; set; }
        public virtual DbSet<Supplier_Master> Supplier_Master { get; set; }
        public virtual DbSet<OrderQty_Mst> OrderQty_Mst { get; set; }
        public virtual DbSet<PouchName_Mst> PouchName_Mst { get; set; }
        public virtual DbSet<RetProductMst> RetProductMsts { get; set; }
        public virtual DbSet<EducationSlab_Mst> EducationSlab_Mst { get; set; }
        public virtual DbSet<SurchargeSlab_Mst> SurchargeSlab_Mst { get; set; }
        public virtual DbSet<TaxSlab_Mst> TaxSlab_Mst { get; set; }
        public virtual DbSet<FormSixteenDetail_Mst> FormSixteenDetail_Mst { get; set; }
        public virtual DbSet<FormSixteenTexableIncome> FormSixteenTexableIncomes { get; set; }
        public virtual DbSet<ColdStorage_InwardQty_Mst> ColdStorage_InwardQty_Mst { get; set; }
        public virtual DbSet<GroundStock_Mst> GroundStock_Mst { get; set; }
        public virtual DbSet<GroundStock_Inward_Mst> GroundStock_Inward_Mst { get; set; }
        public virtual DbSet<ColdStorage_Mst> ColdStorage_Mst { get; set; }
        public virtual DbSet<GroundStockTransfer_Mst> GroundStockTransfer_Mst { get; set; }
        public virtual DbSet<Product_Mst> Product_Mst { get; set; }
        public virtual DbSet<GroundStockTransfer_Inward_Mst> GroundStockTransfer_Inward_Mst { get; set; }
        public virtual DbSet<GroundStock_Outward_Mst> GroundStock_Outward_Mst { get; set; }
        public virtual DbSet<RetProductQtyMst> RetProductQtyMsts { get; set; }
        public virtual DbSet<ColdStorage_Inward_Mst> ColdStorage_Inward_Mst { get; set; }
        public virtual DbSet<ColdStorage_Outward_Mst> ColdStorage_Outward_Mst { get; set; }
        public virtual DbSet<WholeMaterial_Mst> WholeMaterial_Mst { get; set; }
        public virtual DbSet<PowderSpices_Mst> PowderSpices_Mst { get; set; }
        public virtual DbSet<PreMix_Mst> PreMix_Mst { get; set; }
        public virtual DbSet<PreMixQty_Mst> PreMixQty_Mst { get; set; }
        public virtual DbSet<RetCustomerProductDiscountMst> RetCustomerProductDiscountMsts { get; set; }
        public virtual DbSet<RetCustomerCategoryDiscountMst> RetCustomerCategoryDiscountMsts { get; set; }
        public virtual DbSet<RetOrderQtyMst> RetOrderQtyMsts { get; set; }
        public virtual DbSet<CheckReturn_Mst> CheckReturn_Mst { get; set; }
        public virtual DbSet<RetCheckReturn_Mst> RetCheckReturn_Mst { get; set; }
        public virtual DbSet<RetPaymentMst> RetPaymentMsts { get; set; }
        public virtual DbSet<Payment_Mst> Payment_Mst { get; set; }
        public virtual DbSet<FormSixteen_Mst> FormSixteen_Mst { get; set; }
        public virtual DbSet<SalarySheet_Master> SalarySheet_Master { get; set; }
    }
}
