//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vb.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WholeMaterial_Mst
    {
        public long MaterialID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public Nullable<decimal> APMC { get; set; }
        public Nullable<decimal> APMCAmount { get; set; }
        public Nullable<decimal> MarketFinal { get; set; }
        public Nullable<decimal> GrossRate { get; set; }
        public Nullable<decimal> KG_P_Hour { get; set; }
        public Nullable<decimal> Labour_P_Hour { get; set; }
        public Nullable<decimal> Gasara { get; set; }
        public Nullable<decimal> GasaraAmount { get; set; }
        public Nullable<decimal> SellRateWholesale { get; set; }
        public Nullable<decimal> SellRateRetail { get; set; }
        public Nullable<decimal> MarginWholesale { get; set; }
        public Nullable<decimal> MarginRetail { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> PackingCharge { get; set; }
        public Nullable<decimal> Freight_P_KG { get; set; }
        public Nullable<decimal> Commision_P_KG { get; set; }
        public Nullable<decimal> LabourAmount_P_KG { get; set; }
        public Nullable<decimal> Padtar { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
