name: Mvc Build.Legacy.CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2022
    

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore virakibrothers.sln

    - name: Build Solution
      run: |
        msbuild  virakibrothers.sln  /p:DeployOnBuild=true /p:Configuration=Release /p:PublishProfile="virakibrothers"  /p:PublishUrl="../_build"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: EZRepBundle
        path: "./_build"        
        
    
    
          
