name: Mvc Build

on:
  push:
    branches: master

jobs:
  job_1:
    name: build
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
   
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _publish
      
      - name: Restore Packages
        run: nuget restore virakibrothers.sln

      - name: Build Solution
        run: |
         msbuild vbwebsite/vbwebsite.csproj /p:DeployOnBuild=true /p:Configuration=Release /p:PublishProfile="virakibrothers" /p:PublishUrl="../_publish"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: my-artifact
          path: "./_publish"
        
  job_2:
    
      name: deploy artifact
      needs: job_1
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: Download publish code from job 1
          uses: actions/download-artifact@v3
          with:
           name: my-artifact
           path: "./_publish"
        - name: copy file via ssh password
          uses: appleboy/scp-action@v0.1.4
          with:
           host: 52.66.207.204
           username: Administrator
           password: ${{ secrets.PASSWORD }}
           port: 22
           source: "_publish/*"
           target: C:\inetpub\wwwroot\viraki
           script: iisreset /noforce
